CREATE TABLE IF NOT EXISTS disks (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    model TEXT NOT NULL,
    path TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    disk_id TEXT NOT NULL,
    kind TEXT NOT NULL,
    FOREIGN KEY (disk_id) REFERENCES disks(id)
);
